name: Blog – TTN
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts from TTN.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "http://fetchrss.com/rss/64abd179615f713b7c626df364abd1582475ab311b7c5fc2.xml"
          comment_tag_name: "TTN"
          commit_message: "Updated readme with the latest TTN blog posts."
          committer_username: André lademann
          committer_email: vergissberlin@googlemail.com
          disable_item_validation: true
          max_post_count: 10

