name: CodeStats NodeJS – README

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update readme
        uses: vergissberlin/codestats-readme@master
        with:
          CODESTATS_USERNAME: vergissberlin
          SHOW_TITLE: true
          SHOW_LINK: true
          DEBUG: true
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: echo "Dirk" >> README.md
      - run: ls -lisah
      - run: git status
      - run: git config --global user.email "vergissberlin@googlemail.com"
      - run: git config --global user.name "ALA"
      - run: git commit -am"Add a Dirk"
      - run: git remote -v
      - run: git push
      - run: env
        env:
          CODESTATS_USERNAME: vergissberlin
          SHOW_TITLE: true
          SHOW_LINK: true
          DEBUG: true
