name: CodeStats NodeJS – README

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn
      - run: ls -lisah
      - run: env
      - run: node index.js
        env:
          CODESTATS_USERNAME: vergissberlin
          SHOW_TITLE: true
          SHOW_LINK: true
          DEBUG: true
