name: Posts – Blog
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@andre.lademann" # https://dev.to/feed/vergissberlin
          commit_message: "Updated readme with the latest Medium blog posts."
          committer_username: André lademann
          committer_email: vergissberlin@googlemail.com

