name: Posts – stack overflow
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "STACKOVERFLOW"
          commit_message: "Updated readme with the latest StackOverflow data"
          committer_username: André lademann
          committer_email: vergissberlin@googlemail.com
          feed_list: "https://stackoverflow.com/feeds/user/4604831"
